version: '3'
services:
  backend:
    build:
      dockerfile: Dev.Dockerfile
      context: .
    volumes:
    - ./:/deno
    env_file:
      - .env
    ports:
    - 127.0.0.1:8000:8000
    restart: unless-stopped
