export interface Tag {
  "tag_id": string
  "is_auto": boolean
  "localization_names": {
    "bg-bg": string
    "cs-cz": string
    "da-dk": string
    "de-de": string
    "el-gr": string
    "en-us": string
    "es-es": string
    "es-mx": string
    "fi-fi": string
    "fr-fr": string
    "hu-hu": string
    "it-it": string
    "ja-jp": string
    "ko-kr": string
    "nl-nl": string
    "no-no": string
    "pl-pl": string
    "pt-br": string
    "pt-pt": string
    "ro-ro": string
    "ru-ru": string
    "sk-sk": string
    "sv-se": string
    "th-th": string
    "tr-tr": string
    "vi-vn": string
    "zh-cn": string
    "zh-tw": string
  },
  "localization_descriptions": {
    "bg-bg": string
    "cs-cz": string
    "da-dk": string
    "de-de": string
    "el-gr": string
    "en-us": string
    "es-es": string
    "es-mx": string
    "fi-fi": string
    "fr-fr": string
    "hu-hu": string
    "it-it": string
    "ja-jp": string
    "ko-kr": string
    "nl-nl": string
    "no-no": string
    "pl-pl": string
    "pt-br": string
    "pt-pt": string
    "ro-ro": string
    "ru-ru": string
    "sk-sk": string
    "sv-se": string
    "th-th": string
    "tr-tr": string
    "vi-vn": string
    "zh-cn": string
    "zh-tw": string
  }
}
